Update 1.0.0
callistoteam/schoolbot pull request #28
Opened 2020-08-18 00:13 UTC by SaidBySolo

2020-08-22 03:10 UTC, wonderlandpark requested changes
embed에서 역할 색이든 예쁜 색이든 색을 좀 넣으면 좋을거 같습니다.
또한 저번에 말씀드렸던 footer에 timestamp를 넣어주세요

2020-08-22 03:11 UTC, SaidBySolo commented
> embed에서 역할 색이든 예쁜 색이든 색을 좀 넣으면 좋을거 같습니다.
> 또한 저번에 말씀드렸던 footer에 timestamp를 넣어주세요

#35 이슈에있습니다. 참고해주세요

2020-08-22 03:13 UTC, wonderlandpark commented
> > embed에서 역할 색이든 예쁜 색이든 색을 좀 넣으면 좋을거 같습니다.
> > 또한 저번에 말씀드렸던 footer에 timestamp를 넣어주세요
> 
> #35 이슈에있습니다. 참고해주세요

#35 먼저 해결하고 1.0.0으로 올려주시기 바랍니다.

2020-08-22 03:13 UTC, kijk2869 requested changes
이 코드 리뷰는 깃허브에서 작성되었습니다.
모든 코드 제안에는 주변 코드의 탭 검토가 필요합니다.
코드 제안을 바로 커밋하지 마십시오.

2020-08-22 03:13 UTC, kijk2869 commented on schoolbot/cogs/general/help.py
> +        )
```suggestion
        embed = discord.Embed(title="도움말", description="접두사: ``?``") \
            add_field(
                name="급식",
                value="설명:해당학교의 급식정보를 알려줍니다. 날짜가 주어지지 않았을경우 현재 날짜로 가져옵니다.\n인자값: 학교명(필수) 날짜(선택)\n예시:\n?급식 인천기계공업고등학교\n?급식 인천기계공업고등학교 20200810",
                inline=False,
            ) \
            .add_field(
                name="시간표",
                value="설명:해당학교의 시간표를 알려줍니다. 날짜가 주어지지 않았을경우 현재 날짜로 가져옵니다. 현재 고등학교는 가져올수 없습니다.\n인자값: 학교명(필수) 학년(필수) 반(필수) 날짜(선택)\n예시:\n?시간표 구월중학교 2 1\n?시간표 구월중학교 2 1 20200810",
                inline=False,
            ) \ 
            .add_field(
                name="학사일정",
                value="설명:해당학교의 학사정보를 알려줍니다. 날짜가 주어지지 않았을경우 현재 날짜로 가져옵니다.\n인자값: 학교명(필수) 날짜(선택)\n예시:\n?학사일정 인천기계공업고등학교\n?학사일정 인천기계공업고등학교 20200808",
                inline=False,
            ) \ 
            .add_field(
                name="게시물",
                value="설명:해당학교의 아이엠스쿨 게시물을 가져옵니다.\n인자값: 학교명(필수)\n예시:\n?게시물 인천기계공업고등학교",
                inline=False,
            )
```

2020-08-22 03:13 UTC, kijk2869 commented on schoolbot/cogs/school/academic_schedule.py
> +                    )
Can cause code duplicate

Use `discord.on_error` or `await Client.on_error`

2020-08-22 03:13 UTC, kijk2869 commented on schoolbot/cogs/school/academic_schedule.py
> +                )
Can cause code duplicate

Use `discord.on_error` or `await Client.on_error`

2020-08-22 03:13 UTC, kijk2869 commented on schoolbot/cogs/school/article.py
> +                    )
Can cause code duplicate

Use `discord.on_error` or `await Client.on_error`

2020-08-22 03:13 UTC, kijk2869 commented on schoolbot/cogs/school/article.py
> +                )
Can cause code duplicate

Use `discord.on_error` or `await Client.on_error`

2020-08-22 03:13 UTC, kijk2869 commented on schoolbot/cogs/school/meal.py
> +                    )
Can cause code duplicate

Use `discord.on_error` or `await Client.on_error`

2020-08-22 03:13 UTC, kijk2869 commented on schoolbot/cogs/school/meal.py
> +
Can cause code duplicate

Use `discord.on_error` or `await Client.on_error`

2020-08-22 03:13 UTC, kijk2869 commented on schoolbot/cogs/school/timetable.py
> +                    )
Can cause code duplicate

Use `discord.on_error` or `await Client.on_error`

2020-08-22 03:13 UTC, kijk2869 commented on schoolbot/cogs/school/timetable.py
> +            )
`scclass` can be undefined

```suggestion
        if "초등학교" in SN:
            scclass = "els"
        elif "중학교" in SN:
            scclass = "mis"
        elif "고등학교" in SN:
            return await msg.edit(
                embed=discord.Embed(title="죄송합니다. 현재 고등학교는 지원하지않습니다.")  # 고등학교 지원할때 빼면됨
            )
        else:
            return await msg.edit(
                embed=discord.Embed(title="죄송합니다. 지원하지 않는 학교입니다.")
            )
```

2020-08-22 03:13 UTC, kijk2869 commented on schoolbot/cogs/school/academic_schedule.py
> +                    )
```suggestion
            except DataNotFound:
                return await msg.edit(
                    embed=discord.Embed(title="정보가 없습니다. 확인하신후 다시 요청하세요")
                )
            except Exception as e:
```

2020-08-22 03:13 UTC, kijk2869 commented on schoolbot/cogs/school/academic_schedule.py
> +                        SE = choice["SD_SCHUL_CODE"]
```suggestion
                else:
                    fetch_msg = await ctx.fetch_message(response.id)
                    try:
                        num = int(fetch_msg.content) - 1
                    except ValueError:
                        return await msg.edit(
                            embed=discord.Embed(title="잘못된값을 주셨습니다. 처음부터 다시 시도해주세요.")
                        )
                    
                    choice = scinfo.data[num]
                    AE = choice["ATPT_OFCDC_SC_CODE"]
                    SE = choice["SD_SCHUL_CODE"]
```

2020-08-22 03:13 UTC, kijk2869 commented on schoolbot/cogs/school/academic_schedule.py
> +                        )
Hardcoded

Use `str.isdigit()`

2020-08-22 03:13 UTC, kijk2869 commented on schoolbot/cogs/school/academic_schedule.py
> +                )
```suggestion
        except DataNotFound:
            return await msg.edit(
                embed=discord.Embed(title="정보가 없습니다. 확인하신후 다시 요청하세요")
            )
        except Exception as e:
```

2020-08-22 03:13 UTC, kijk2869 commented on schoolbot/cogs/school/article.py
> +                    )
```suggestion
            except HTTPException:
                return await msg.edit(
                    embed=discord.Embed(title="HTTP 요청 오류입니다", description=f"{e}")
                )
            except Exception as e:
```

2020-08-22 03:13 UTC, kijk2869 commented on schoolbot/cogs/school/article.py
> +                if scinfo == []:
```suggestion
                if not scinfo:
```

2020-08-22 03:13 UTC, kijk2869 commented on schoolbot/cogs/school/article.py
> +                    if len(scinfo) > 1:
```suggestion
                    if scinfo:
```

2020-08-22 03:13 UTC, kijk2869 commented on schoolbot/cogs/school/academic_schedule.py
> +            if len(scinfo.data) > 1:
```suggestion
            if scinfo.data:
```

2020-08-22 03:13 UTC, kijk2869 commented on schoolbot/cogs/school/article.py
> +                                )
Hardcoded

Use `str.isdigit()`

2020-08-22 03:13 UTC, kijk2869 commented on schoolbot/cogs/school/article.py
> +                                choice = scinfo[num]
```suggestion
                            choice = scinfo[num]
```

2020-08-22 03:13 UTC, kijk2869 commented on schoolbot/cogs/school/article.py
> +            else:
```suggestion
        except HTTPException:
            return await msg.edit(
                embed=discord.Embed(title="HTTP 요청 오류입니다", description=f"{e}")
            )
        except Exception as e:
```

2020-08-22 03:13 UTC, kijk2869 commented on schoolbot/cogs/school/article.py
> +            if scarticles == []:
```suggestion
            if not scarticles:
```

2020-08-22 03:13 UTC, kijk2869 commented on schoolbot/cogs/school/meal.py
> +                else:
```suggestion
            except DataNotFound:
                if isinstance(e, DataNotFound):
                    return await msg.edit(
                        embed=discord.Embed(title="정보가 없습니다. 확인하신후 다시 요청하세요")
                    )
            except Exception as e:
```

2020-08-22 03:13 UTC, kijk2869 commented on schoolbot/cogs/school/meal.py
> +            if len(scinfo.data) > 1:
```suggestion
            if scinfo.data:
```

2020-08-22 03:13 UTC, kijk2869 commented on schoolbot/cogs/school/meal.py
> +                    fetch_msg = await ctx.fetch_message(response.id)
Why fetch again?

2020-08-22 03:13 UTC, kijk2869 commented on schoolbot/cogs/school/academic_schedule.py
> +                    fetch_msg = await ctx.fetch_message(response.id)
Why fetch again?

2020-08-22 03:13 UTC, kijk2869 commented on schoolbot/cogs/school/meal.py
> +                        )
Hardcoded

Use `str.isdigit`

2020-08-22 03:13 UTC, kijk2869 commented on schoolbot/cogs/school/meal.py
> +                        SE = choice["SD_SCHUL_CODE"]
```suggestion
                    choice = scinfo.data[num]
                    AE = choice["ATPT_OFCDC_SC_CODE"]
                    SE = choice["SD_SCHUL_CODE"]
```

2020-08-22 03:13 UTC, kijk2869 commented on schoolbot/cogs/school/meal.py
> +            else:
```suggestion
        except DataNotFound:
            return await msg.edit(
                embed=discord.Embed(title="정보가 없습니다. 확인하신후 다시 요청하세요")
            )
        except Exception as e:
```

2020-08-22 03:13 UTC, kijk2869 commented on schoolbot/cogs/school/meal.py
> +                description=meal,
```suggestion
        await msg.edit(
            embed=discord.Embed(
                title=f"{scmeal.SCHUL_NM}의 급식입니다.\n\n{meal_day[0:4]}년 {meal_day[4:6]}월 {meal_day[6:8]}일",
                description=scmeal.DDISH_NM.replace("<br/>", "\n"),
```

2020-08-22 03:13 UTC, kijk2869 commented on schoolbot/cogs/school/timetable.py
> +                else:
```suggestion
            except DataNotFound:
                return await msg.edit(
                    embed=discord.Embed(title="정보가 없습니다. 확인하신후 다시 요청하세요")
                )
            except Exception as e:
```

2020-08-22 03:13 UTC, kijk2869 commented on schoolbot/cogs/school/timetable.py
> +            if len(scinfo.data) > 1:
```suggestion
            if scinfo.data:
```

2020-08-22 03:13 UTC, kijk2869 commented on schoolbot/cogs/school/timetable.py
> +                    fetch_msg = await ctx.fetch_message(response.id)
Why fetch again?

2020-08-22 03:13 UTC, kijk2869 commented on schoolbot/cogs/school/timetable.py
> +                        )
Hardcoded

Use `str.isdigit()`

2020-08-22 03:13 UTC, kijk2869 commented on schoolbot/cogs/school/timetable.py
> +                        SN = choice["SCHUL_NM"]
```suggestion
                    choice = scinfo.data[num]
                    AE = choice["ATPT_OFCDC_SC_CODE"]
                    SE = choice["SD_SCHUL_CODE"]
                    SN = choice["SCHUL_NM"]
```

2020-08-22 03:13 UTC, kijk2869 commented on schoolbot/cogs/school/timetable.py
> +                )
```suggestion
        except DataNotFound:
            return await msg.edit(
                embed=discord.Embed(title="정보가 없습니다. 확인하신후 다시 요청하세요")
            )
        except Exception as e:
```

2020-08-22 03:14 UTC, SaidBySolo commented
> > > embed에서 역할 색이든 예쁜 색이든 색을 좀 넣으면 좋을거 같습니다.
> > > 또한 저번에 말씀드렸던 footer에 timestamp를 넣어주세요
> > 
> > 
> > #35 이슈에있습니다. 참고해주세요
> 
> #35 먼저 해결하고 1.0.0으로 올려주시기 바랍니다.

wait라벨 참고해 주시기 바랍니다. 아직 머지해서는 안되는 풀리퀘입니다.

2020-08-22 03:14 UTC, wonderlandpark commented
> > > > embed에서 역할 색이든 예쁜 색이든 색을 좀 넣으면 좋을거 같습니다.
> > > > 또한 저번에 말씀드렸던 footer에 timestamp를 넣어주세요
> > > 
> > > 
> > > #35 이슈에있습니다. 참고해주세요
> > 
> > 
> > #35 먼저 해결하고 1.0.0으로 올려주시기 바랍니다.
> 
> wait라벨 참고해 주시기 바랍니다. 아직 머지해서는 안되는 풀리퀘입니다.

확인했습니다

2020-08-24 00:49 UTC, kijk2869 commented
will reopen

2020-08-25 03:30 UTC, wonderlandpark requested changes, later dismissed

2020-08-25 03:30 UTC, wonderlandpark commented on README.md
> +> A discord bot that informs the school's academic calendar, timetable, and meals in South Korea
Republic of Korea

2020-08-25 03:30 UTC, wonderlandpark commented on schoolbot/cogs/general/help.py
> +    @commands.command(name="도움말", aliases=["help"])
aliases: 도움, commands, 명령어 등등

2020-08-25 03:30 UTC, wonderlandpark commented on schoolbot/cogs/school/meal.py
> +                title="정보를 요청합니다 잠시만 기다려주세요.", colour=discord.Colour.blurple()
check command syntax first

(`정보를 요청합니다` 잠시만 기다려주세요가 `학교명을 입력해주세요` 보다 먼저 표시됨)

2020-08-25 03:30 UTC, wonderlandpark commented on schoolbot/cogs/school/meal.py
> +                # 대충 여따가 쿼리문 적으면 된다는 주석
주석 지우시는게 좋을거 같습니다.

2020-08-25 03:30 UTC, wonderlandpark commented on schoolbot/cogs/school/timetable.py
> +                title="정보를 요청합니다 잠시만 기다려주세요.", colour=discord.Colour.blurple()
check command syntax first

(`정보를 요청합니다 잠시만 기다려주세요`가 `학년과 반정보를 입력해주세요!` 보다 먼저 표시됨)

2020-08-27 01:17 UTC, kijk2869 requested changes

2020-08-27 01:17 UTC, kijk2869 commented on .github/workflows/python-app-lint.yml
> +        pip install flake8 black
Installing requirements deleted

2020-08-27 01:17 UTC, kijk2869 commented on schoolbot/cogs/events/error.py
> +            trace_embed.set_footer(text=kst_sft())
How about use timestamp

2020-08-27 01:17 UTC, kijk2869 commented on schoolbot/cogs/general/search.py
> +                    fetch_msg = await ctx.fetch_message(response.id)
Message refetched

2020-08-27 01:17 UTC, kijk2869 commented on schoolbot/cogs/general/setting.py
> +            args = " ".join(value.split("|")).split()
Same as `args = value.split("|")`

2020-08-27 01:17 UTC, kijk2869 commented on schoolbot/cogs/school/academic_schedule.py
> +            (date == None and school_name == None)
```suggestion
            not (date and school_name)
```

2020-08-27 01:17 UTC, kijk2869 commented on schoolbot/cogs/school/article.py
> +                while True:
```suggestion
                while not self.bot.is_closed():
```

2020-08-27 01:17 UTC, kijk2869 commented on schoolbot/cogs/school/meal.py
> +            (date == None and school_name == None)
```suggestion
            not (date and school_name)
```

2020-08-27 01:17 UTC, kijk2869 commented on schoolbot/cogs/school/timetable.py
> +                        fetch_msg = await ctx.fetch_message(response.id)
Unused variable

2020-08-27 01:17 UTC, kijk2869 commented on schoolbot/cogs/school/timetable.py
> +                embed=discord.Embed(title=f"{tt_scname}", colour=0x2E3136,)
```suggestion
                embed=discord.Embed(title=tt_scname, colour=0x2E3136,)
```

2020-08-27 23:04 UTC, SaidBySolo commented on schoolbot/cogs/school/meal.py
> +                title="정보를 요청합니다 잠시만 기다려주세요.", colour=discord.Colour.blurple()
의도한것입니다.

2020-08-27 23:10 UTC, SaidBySolo commented on schoolbot/cogs/school/timetable.py
> +                title="정보를 요청합니다 잠시만 기다려주세요.", colour=discord.Colour.blurple()
의도한것이지만 수정하겠습니다.

2020-08-28 01:37 UTC, kijk2869 commented
이제 슬슬 머지하자 ㅅㅂ 이 pr에만 164커밋이야

2020-08-28 01:37 UTC, Yoruroong commented
PR에 164커밋있는거 처음봄

2020-08-28 01:38 UTC, SaidBySolo commented
not resolve https://github.com/callistoteam/schoolbot/pull/28#discussion_r477845290

2020-08-28 02:52 UTC, kijk2869 approved these changes, later dismissed

2020-08-28 16:26 UTC, kijk2869 approved these changes

2020-08-28 16:27 UTC, wonderlandpark approved these changes
LSTM

2020-08-28 16:27 UTC, merged