feat: aiomysql
callistoteam/schoolbot pull request #49
Opened 2020-08-23 11:30 UTC by COIN-KR

2020-08-23 11:38 UTC, kijk2869 requested changes
Suggest to use `SQLAlchemy`

2020-08-23 11:38 UTC, kijk2869 commented on schoolbot/cogs/general/search.py
> +        self.neis = neispy.AsyncClient(apikey)
```suggestion
import os
import neispy
from neispy import DataNotFound
import discord
from discord.ext import commands


class Search(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
        self.neis = neispy.AsyncClient(os.environ["API_KEY"])
```

2020-08-23 11:38 UTC, kijk2869 commented on schoolbot/cogs/general/__init__.py
> +    bot.add_cog(Search(bot, os.environ["API_KEY"]))
```suggestion
    bot.add_cog(Search(bot))
```

2020-08-23 11:38 UTC, kijk2869 commented on schoolbot/cogs/general/__init__.py
> +
```suggestion
```

2020-08-23 11:48 UTC, SaidBySolo requested changes

2020-08-23 11:48 UTC, SaidBySolo commented on schoolbot/cogs/school/meal.py
> +                    )
```suggestion
            except DataNotFound:
                return await msg.edit(
                    embed=discord.Embed(title="정보가 없습니다. 확인하신후 다시 요청하세요")
                )
```

2020-08-23 11:48 UTC, SaidBySolo commented on schoolbot/cogs/general/search.py
> +
```suggestion

```

2020-08-23 11:48 UTC, SaidBySolo commented on schoolbot/cogs/general/search.py
> +            if len(scinfo.data) > 1:
```suggestion
            except DataNotFound:
                return await msg.edit(
                    embed=discord.Embed(title="정보가 없습니다. 확인하신후 다시 요청하세요")
                )
```

2020-08-23 11:50 UTC, SaidBySolo commented on schoolbot/cogs/general/search.py
> +            if len(scinfo.data) > 1:
missed in 36 line

2020-08-23 11:55 UTC, SaidBySolo requested changes

2020-08-23 11:55 UTC, SaidBySolo commented on schoolbot/cogs/general/search.py
> +                        )
```suggestion
                            if response.content.isdigit():
                                num = response.content - 1
                            else:
                                return await msg.edit(
                                    embed=discord.Embed(
                                        title="잘못된값을 주셨습니다. 처음부터 다시 시도해주세요."
                                    )
                                )
```

2020-08-23 12:11 UTC, SaidBySolo requested changes

2020-08-23 12:11 UTC, SaidBySolo commented on schoolbot/cogs/school/timetable.py
> +                            )
```suggestion
                            if response.content.isdigit():
                                num = response.content - 1
                            else:
                                return await msg.edit(
                                    embed=discord.Embed(
                                        title="잘못된값을 주셨습니다. 처음부터 다시 시도해주세요."
                                    )
                                )
```

2020-08-23 12:11 UTC, SaidBySolo commented on schoolbot/cogs/school/meal.py
> +                            )
```suggestion
                            if response.content.isdigit():
                                num = response.content - 1
                            else:
                                return await msg.edit(
                                    embed=discord.Embed(
                                        title="잘못된값을 주셨습니다. 처음부터 다시 시도해주세요."
                                    )
                                )
```

2020-08-23 12:11 UTC, SaidBySolo commented on schoolbot/cogs/school/academic_schedule.py
> +                            )
```suggestion
                            if response.content.isdigit():
                                num = response.content - 1
                            else:
                                return await msg.edit(
                                    embed=discord.Embed(
                                        title="잘못된값을 주셨습니다. 처음부터 다시 시도해주세요."
                                    )
                                )
```

2020-08-23 12:34 UTC, SaidBySolo submitted a review, later dismissed
수고하셨어요 ㅠㅠㅠㅠㅠ

2020-08-23 12:42 UTC, kijk2869 requested changes

2020-08-23 12:42 UTC, kijk2869 commented on schoolbot/cogs/school/academic_schedule.py
>                          )
@SaidBySolo 이거 따로 뺀거 아니었음?

2020-08-23 12:42 UTC, kijk2869 commented on schoolbot/cogs/general/search.py
> +            scclass = "his"
```suggestion
        if "초등학교" in SN:
            scclass = "els"
        elif "중학교" in SN:
            scclass = "mis"
        elif "고등학교" in SN:
            scclass = "his"
        else:
            raise ValueError
```

2020-08-23 12:42 UTC, kijk2869 commented on schoolbot/cogs/school/timetable.py
> +
Need `else`

2020-08-23 12:43 UTC, SaidBySolo commented on schoolbot/cogs/school/academic_schedule.py
>                          )
나 저건 따로 뺀기억이 없음

2020-08-23 12:58 UTC, SaidBySolo requested changes
이게 마지막이 되길...

2020-08-23 12:58 UTC, SaidBySolo commented on schoolbot/cogs/school/timetable.py
> +                raise ValueError
```suggestion
        else:
            return await msg.edit(
                embed=discord.Embed(
                    title="죄송합니다. 지원하지 않는 학교입니다.", colour=discord.Colour.red()
                )
            )
```

2020-08-24 11:25 UTC, SaidBySolo approved these changes
수고하셨습니다.

2020-08-24 12:08 UTC, kijk2869 approved these changes

2020-08-24 12:10 UTC, merged