Release 1.0.0
callistoteam/schoolbot pull request #64
Opened 2020-08-28 16:33 UTC by wonderlandpark

2020-09-05 02:22 UTC, SaidBySolo commented
@kijk2869 @COIN-KR @SaidBySolo 

마지막 검토 예정

2020-09-05 02:23 UTC, SaidBySolo submitted a review, later dismissed
LGFM

2020-09-05 02:37 UTC, kijk2869 requested changes

2020-09-05 02:37 UTC, kijk2869 commented on schoolbot/cogs/general/search.py
> +        embed = discord.Embed(title="검색 정보", description="")
```suggestion
        embed = discord.Embed(title="검색 정보")
```

2020-09-05 02:37 UTC, kijk2869 commented on schoolbot/cogs/general/setting.py
> +
```suggestion
import re

```

2020-09-05 02:37 UTC, kijk2869 commented on schoolbot/cogs/general/setting.py
> +            args = " ".join(value.split("|")).split()
```suggestion
            args = re.split(r"\||\s", value)
```

2020-09-05 02:37 UTC, kijk2869 commented on schoolbot/cogs/school/article.py
> +                await msg.add_reaction("▶")
```suggestion
                Bot.loop.create_task(asyncio.wait([msg.add_reaction(emoji) for emoji in ["◀", "⏹", "▶"]]))
```

2020-09-05 02:37 UTC, kijk2869 commented on schoolbot/db.py
> +            return
```suggestion
async def create_user_data(**kwargs):
    async with pool.acquire() as conn:
        async with conn.cursor() as cur:
            await cur.execute(
                "INSERT INTO `users`(`id`, `neis_ae`, `neis_se`, `grade`, `class_nm`, `class`) VALUES (%(id)s,%(neis_ae)s,%(neis_se)s,%(grade)s,%(class_nm)s,%(scclass)s);",
                kwargs,
            )
            return
```

2020-09-05 02:37 UTC, kijk2869 commented on schoolbot/db.py
> +            return
```suggestion
async def update_school(**kwargs):
    async with pool.acquire() as conn:
        async with conn.cursor() as cur:
            await cur.execute(
                "UPDATE `users` SET `neis_ae` = %(neis_ae)s, `neis_se` = %(neis_se)s, `grade` = %(grade)s, `class_nm` = %(class_nm)s, `class` = %(class)s WHERE ID = %(id)s;",
                kwargs,
            )
            return
```

2020-09-05 02:37 UTC, kijk2869 commented on utils/kst.py
> +    return datetime.datetime.now(tz=KST)
```suggestion
KST = datetime.timezone(datetime.timedelta(hours=9))

def korean_date():
    return datetime.datetime.now(tz=KST)
```

2020-09-05 02:47 UTC, SaidBySolo commented on schoolbot/cogs/school/article.py
> +                await msg.add_reaction("▶")
self.bot?

2020-09-05 02:51 UTC, kijk2869 commented on schoolbot/cogs/school/article.py
> +                await msg.add_reaction("▶")
My mistake, Bot -> self.bot

2020-09-05 17:34 UTC, kijk2869 commented
close #56 
close #75

2020-09-05 17:37 UTC, kijk2869 approved these changes, later dismissed
내가 한건데 시발 어프루브지

2020-09-06 02:47 UTC, SaidBySolo submitted a review, later dismissed

2020-09-06 11:09 UTC, kijk2869 commented
나 이거 걍 머지한다? 이제 1.0.0이 아닌듯

2020-09-06 11:11 UTC, SaidBySolo approved these changes

2020-09-06 11:11 UTC, SaidBySolo commented
force merge

2020-09-06 11:11 UTC, kijk2869 approved these changes

2020-09-06 11:12 UTC, merged